[ai]
model = "anthropic/claude-3.5-sonnet"
api_url = "https://openrouter.ai/api/v1"
temperature = 0.4
max_tokens = 1000
timeout = 45

[format]
max_subject_length = 70
require_body_for_features = true
enforce_conventional = true
allowed_types = ["feat", "fix", "docs", "style", "refactor", "perf", "test", "build", "ci", "chore", "revert"]

[diff]
context_reserve = 4000
char_per_line_ratio = 80
